version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: ../backend
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/:/usr/share/nginx/frontend/
      - ../docs/:/usr/share/nginx/frontend/api/docs/
      - static_data:/usr/share/nginx/static/
      - media_data:/usr/share/nginx/media/

volumes:
  db_data:
  media_data:
  static_data:

