# Generated by Django 2.2.16 on 2022-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20220804_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
