# Generated by Django 2.2.16 on 2022-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_auto_20220804_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
