# Generated by Django 2.2.16 on 2022-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0010_auto_20220806_2225'),
        ('users', '0004_auto_20220804_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorited_by', to='foodgram.Recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart_recipes',
            field=models.ManyToManyField(related_name='added_to_shopping_cart_by', to='foodgram.Recipe'),
        ),
    ]
